### PR TITLE
Fix subject and fields parsing issues

### PR DESCRIPTION
**Pull request by ekutner**

### CODE REVIEW

**Review by HandyGuySoftware — COMMENTED** [review]
Interesting changes. I like how the parsing code is streamlined a bit. With the exception of allowing spaces around the delimiter, do you have an example of a subject line that did not work under the old parser that does work under the new one?

**Comment by HandyGuySoftware** [comment]
I ran through a couple of quick tests and it seems to be working. I'm going to run it in the lab environment here for a few days and make sure nothing crops up. I'll let you know how it goes.

**Comment by ekutner** [comment]
Well, no subject line worked for me. I looked back at the original code, trying to figure out how it could have worked before  and now I realized that there was probably an implicit assumption that the source/dest names were single words, without spaces. I didn't realize that before and so my source name had spaces in it (it makes sense in my case because I have multiple jobs per machine). 
That said, the new code, if used together with the regular expressions I mentioned in the issue, allows for any string to be used in the source or destination, including spaces.

**Comment by HandyGuySoftware** [comment]
That makes sense. The new code is in testing now. If it's stable for a few days and doesn't produce nay further errors I'll move it into the code base, along with the documentation updates you suggested. Thanks for helping out with this.

**Pull request merged**
