### PR TITLE
Add 'Date' header to email functions for RFC compliance

### PR DESCRIPTION
**Pull request by DocFraggle**
Hi, thanks a lot for your script! 

In order to be compliant with the email RFC I added the 'Date' header. My Android phone for example didn't show the report mail at all because of the missing date header.

Regards, Christian

### CODE REVIEW

**Comment by HandyGuySoftware** [comment]
@DocFraggle , good catch. Strange that this hasn't crashed anyone else yet. I'll probably put out a point release (2.1.1) to address this, but I'm still new to GitHub (and SourceTree) so it may take me a bit to figure out how to put this request into that release. Stay tuned.

**Comment by DocFraggle** [comment]
Hi, after you merge my PR into your master, you can checkout your "2.1.0_Beta" branch, create a new branch "2.1.1_Beta" from this one, and then cherry-pick my commit from the master.

So it would look like this after you merged my PR:

```
> git checkout 2.1.0_Beta
Switched to branch '2.1.0_Beta'
> git checkout -b 2.1.1_Beta
Switched to a new branch '2.1.1_Beta'
> git cherry-pick 9f968db7f22ce1f2cc328f2db2fc68f81f887228  (<-- depending on the commit hash of my change in your master, of course :) )
> git log
commit 2ad19fc38a48b589da55c84b4ef7665c0c8a08bd
Author: Christian Hailer <christian@hailer.eu>
Date:   Sat Jan 20 14:36:58 2018 +0100

    Add 'Date' header to email functions for RFC compliance

commit 55515335558211b2f1138434ca142f57b8ac1aba
Author: HandyGuySoftware <steve@friedfamily.net>
Date:   Sun Jan 7 10:03:21 2018 -0600

    2.1.0 Beta 1 - Change to release status

...
```

**Comment by HandyGuySoftware** [comment]
If I create a new 2.1.1_Beta branch, is there a way to merge the PR directly into that branch? I like to keep the master clean with the latest release until I'm ready to merge a new full release. (Or quite possibly I'm just not understanding how Git/GitHub is supposed to work ;-)

**Comment by DocFraggle** [comment]
Well, it depends on how you want to work with git. At work I mainly follow this git flow model: http://nvie.com/posts/a-successful-git-branching-model/
So you create a development branch. If you test a new feature, you create a new feature branch from there. As soon as you are finished, you merge it back to the development branch. Then, for your upcoming release, you create a release branch. Additional features (like my date field for example) are merged to the development branch first, and afterwards merged from the development branch to the release branch. After a successful release the changes are merged to the master (and to development if you added commits directly on the release branch).

Maybe a bit complicated at first glance, but very efficient :)

Regards, Christian

**Comment by HandyGuySoftware** [comment]
Interesting, so "master" is really just a running tally of all the changes/commits? The release branches are the "gold builds" for each release/beta? I'll need to take a look at what I've been doing and make adjustments.

In any case, your fixes have already made it into the 2.2 code. Since you seem to have it fixed on your end I should have a little time to figure out.

**Comment by HandyGuySoftware** [comment]
@DocFraggle, I really like the method shown in the article, but my repository is really far down the line and I'm finding migrating to be really difficult. At this point, I either need to start from scratch and re-create the history or leave it as is and just use the method for my next project. I'm considering both, but haven't made up my mind yet. I'll let you know what I decide.

**Pull request closed without merging**
